Improve condition for checking if CRD file is a URL
Was stumped by this when attempting to include a local CRD file named `httproutes.gateway.networking.k8s.io.json` - which resulted in the following error:

```
ValueError: unknown url type: 'httproutes.gateway.networking.k8s.io.json'
```

Assuming that all`startsWith("http")` was intended to do is discerning local from remote resource references.